### ISSUE TITLE
GBR occasionally crash, attempt to reload but fail requiring a restart

### ISSUE THREAD

**Issue by NthMetal** [NthMetal/gbraidfinder#14]
GBR Logs:
```
l130 2 187 processing  99CD38A9 with level 130
l151 4 187 processing  80CDDF1C with level 151
{"level":"ERROR","timestamp":"2022-11-22T03:55:01.164Z","logger":"kafkajs","message":"[Runner] Error when calling eachMessage","topic":"l151","partition":4,"offset":"270","stack":"Error: Evaluation failed: SyntaxError: Unexpected token 'T', \"The reques\"... is not valid JSON\n    at ExecutionContext._ExecutionContext_evaluate (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:229:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async ExecutionContext.evaluate (/usr/src/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:107:16)\n    at async AppService.evaluateBattleKey (/usr/src/app/dist/app.service.js:112:16)\n    at async AppService.getRaidInfo (/usr/src/app/dist/app.service.js:96:32)\n    at async Runner.eachMessage (/usr/src/app/dist/kafka.service.js:104:36)\n    at async Runner.processEachMessage (/usr/src/app/node_modules/kafkajs/src/consumer/runner.js:231:9)\n    at async onBatch (/usr/src/app/node_modules/kafkajs/src/consumer/runner.js:447:9)\n    at async Runner.handleBatch (/usr/src/app/node_modules/kafkajs/src/consumer/runner.js:461:5)\n    at async /usr/src/app/node_modules/kafkajs/src/consumer/worker.js:29:9","error":{}}
l120 3 187 processing  EF7A9EA5 with level 120
reloading page
l151 4 187 processing  80CDDF1C with level 151
polling config for changes
```
message with offset 270 partition 4 in topic l151
```
{
"locale":"JP"
"message":""
"battleKey":"80CDDF1C"
"quest_id":"305241"
}
```

More info soon

**Comment by NthMetal** [comment]
possibly fixed with 608a8e06fb83cfa7c125a88ba36c0c735c6822ed

need to confirm
